//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tp2.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tp2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;es&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta content=&quot;text/html&quot; charset=&quot;UTF-8&quot; /&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=1.0&quot; /&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;estilos.css&quot;&gt;
        ///        &lt;title&gt;Índice&lt;/title&gt;
        ///    &lt;/head&gt;
        ///    
        ///    &lt;body&gt;
        ///        &lt;div class=&quot;contenido&quot;&gt;
        ///            &lt;h1&gt;Casa&lt;/h1&gt;
        ///
        ///            &lt;h2&gt;Carga de una Casa&lt;/h2&gt;
        ///            &lt;p&gt;
        ///                No sé.
        ///            &lt;/p&gt;
        ///
        ///            &lt;im [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string casa {
            get {
                return ResourceManager.GetString("casa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a body {
        ///    background-color: #0f0f0f;
        ///}
        ///
        ///* {
        ///    font-family: &apos;Segoe UI&apos;, Tahoma, Geneva, Verdana, sans-serif;
        ///    color: #e8e8e8;
        ///}
        ///
        ///h1, h3 {
        ///    color: white;
        ///}
        ///
        ///h1 {
        ///    font-weight: 1000;
        ///}
        ///
        ///h3 {
        ///    font-family: &apos;Century Gothic&apos;, &apos;Segoe UI&apos;, Tahoma, Geneva, Verdana, sans-serif;
        ///    font-weight: lighter;
        ///    color: white;
        ///}
        ///
        ///.contenido {
        ///    background-color: #1f1f1f;
        ///    margin: 12pt;
        ///    padding: 0pt 8pt 1pt 8pt
        ///}.
        /// </summary>
        internal static string estilos {
            get {
                return ResourceManager.GetString("estilos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;es&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta content=&quot;text/html&quot; charset=&quot;UTF-8&quot; /&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=1.0&quot; /&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;./estilos.css&quot;&gt;
        ///        &lt;title&gt;Índice&lt;/title&gt;
        ///    &lt;/head&gt;
        ///    
        ///    &lt;body&gt;
        ///        &lt;div style=&quot;background-color: #1f1f1f; margin: 12pt; padding: 0pt 8pt 1pt 8pt&quot;&gt;
        ///            &lt;h1&gt;Hotel&lt;/h1&gt;
        ///    
        ///            &lt;p&gt;
        ///                No sé.
        ///             [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string hotel {
            get {
                return ResourceManager.GetString("hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plusblack32 {
            get {
                object obj = ResourceManager.GetObject("plusblack32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xwhite32 {
            get {
                object obj = ResourceManager.GetObject("xwhite32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
